import { NativeModules } from 'react-native';
import { BatchUserEditor } from './BatchUserEditor';
const RNBatch = NativeModules.RNBatch;

/**
 * Batch's user module
 */
export const BatchUser = {
  /**
   * Get the unique installation ID, generated by Batch. Batch must be started to read it.
   * You will get the result in a promise.
   *
   * Android ✅ , iOS ✅
   */
  getInstallationID: (): Promise<string> =>
    RNBatch.userData_getInstallationId(),

  /**
   * Creates an editor for the user profile
   * The profile is not updated until the method `save()` is called
   */
  editor: (): BatchUserEditor => new BatchUserEditor(),
};
